name: movie_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1 # for http request. get movie data from api
  flutter_rating_bar: ^4.0.1 # for display star rating 
  page_indicator: ^0.4.1 # for page view and indicator
  youtube_player_flutter: ^8.1.2 # for import trailers from youtube
  flutter_dotenv: ^5.1.0 # for create .env file, to store api key
  hive: ^2.2.3 # for hive noSQL
  hive_flutter: ^1.1.0 # for hive noSQL type adapter
  hive_generator: ^2.0.0 # for hive noSQL type adapter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.5




flutter:


  uses-material-design: true

  
  assets:
    - .env





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

